### ISSUE TITLE
Conditionally provide program depending on the version

### ISSUE THREAD

**Issue by felipecrs** [pkgxdev/libpkgx#68]
just need to omit it; it would be a potential upgrade to libpkgx if desired.

_Originally posted by @jhheider in https://github.com/pkgxdev/pantry/pull/5468#discussion_r1516599364_

Just to keep this tracked. openjdk 21+ provides `bin/jwebserver` while older versions does not.

It would be nice something like the following were allowed:

```yaml
provides:
  - bin/java
  - program: bin/jwebserver
    if: {{version.major}} >= 21
```
